apiVersion: v1
kind: Service
metadata:
  name: simple-game-server-svc
spec:
  selector:
    app: simple-game-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: 5000-port
      port: 5000
      targetPort: 5000