apiVersion: v1
kind: Service
metadata:
  # name: agones-gameserver
  name: simple-game-server-svc
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: simple-game-server
  ports:
  - protocol: UDP
    port: 7000 # local port
    targetPort: 5000
