# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-nk-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-nk-postgres
  template:
    metadata:
      labels:
        app: template-nk-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          env:
            - name: POSTGRES_DB
              value: nakama
            - name: POSTGRES_PASSWORD
              value: localdb
            - name: POSTGRES_USER
              value: postgres
          command:
            - postgres
            - "-c"
            - "shared_preload_libraries=pg_stat_statements"
            - "-c"
            - "pg_stat_statements.track=all"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - postgres
                - "-d"
                - nakama
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      securityContext:
        runAsUser: 70
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc


---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: template-nk-postgres
spec:
  selector:
    app: template-nk-postgres
  ports:
    - protocol: TCP
      name: 5432-port
      port: 5432
      targetPort: 5432
    - protocol: TCP
      name: 8080-port
      port: 8080
      targetPort: 8080